[package]
name = "ln-gateway"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.0", features = ["attributes", "tokio1"] }
async-trait = "0.1.52"
clightningrpc = { git = "https://github.com/elsirion/rust-clightning-rpc", rev = "28b0b062dfb7d758a3a0753c274febe4a7faa584" }
futures = "0.3.21"
hex = "0.4.3"
lightning-invoice = "0.11.0"
minimint = { path = "../minimint" }
minimint-api = { path = "../minimint-api" }
mint-client = { path = "../mint-client" }
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
sled = "0.34.6"
structopt = "0.3.21"
thiserror = "1.0.30"
tide = "0.16.0"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
tokio = {version = "1.0", features = ["full"]}
