[workspace]

members = [
    "crypto/tbs",
    "ln-gateway",
    "minimint",
    "minimint-derive",
    "minimint-api",
    "mint-client",
    "modules/minimint-mint",
    "modules/minimint-ln",
    "modules/minimint-wallet",
]

[patch.crates-io]
bitcoin_hashes = { version = "0.10.0", git = 'https://github.com/elsirion/bitcoin_hashes', branch = 'minimint' }
secp256k1 = { git = "https://github.com/elsirion/rust-secp256k1.git", branch = "minimint" }